#!/usr/bin/env python3
import os
import re
import subprocess
import sys

args = sys.argv[1:]
root = args[args.index("--root") + 1] if "--root" in args else os.getcwd()
using_real_tree = "--root" not in args

DENYLIST = ["PLAN", "STATUS", "PROGRESS", "ROADMAP", "NOTES", "JOURNAL", "TODO"]
DENY_PATH_PREFIXES = ["docs/plan"]
CHANGELOG_MARKER = "<!-- generated by make changelog -->"
DEFERRAL_TAGS = ["TODO", "FIXME", "HACK", "XXX", "WIP"]

# The interactive GitHub CLI identity: configured per-operator via the
# environment, outside tracked source, so no personal alias is ever a literal
# in this file. Defaults to plain `gh` for anyone without one configured.
GH_INTERACTIVE = os.environ.get("CHRONODUCK_GH_INTERACTIVE_CLI", "gh")


def read_text(path):
    with open(path, "rb") as f:
        raw = f.read()
    if b"\0" in raw:
        return None
    return raw.decode("utf-8", errors="replace")


def list_files(dir_):
    if using_real_tree:
        out = subprocess.run(["git", "-C", dir_, "ls-files"], capture_output=True, text=True).stdout
        return [l for l in out.split("\n") if l]
    files = []

    def walk(d, prefix):
        for entry in os.listdir(d):
            full = os.path.join(d, entry)
            rel = f"{prefix}/{entry}" if prefix else entry
            if os.path.isdir(full):
                walk(full, rel)
            else:
                files.append(rel)

    walk(dir_, "")
    return files


def check_denylist(files):
    violations = []
    for f in files:
        base = f.split("/")[-1]
        for pat in DENYLIST:
            if base.startswith(pat):
                violations.append(f'{f}: filename matches ledger denylist pattern "{pat}*"')
        for prefix in DENY_PATH_PREFIXES:
            if f.startswith(prefix):
                violations.append(f'{f}: path matches ledger denylist pattern "{prefix}*"')
    return violations


def check_changelog(files, dir_):
    violations = []
    if "CHANGELOG.md" in files:
        content = read_text(os.path.join(dir_, "CHANGELOG.md"))
        if content is None or not content.startswith(CHANGELOG_MARKER):
            violations.append(f'CHANGELOG.md: must begin with "{CHANGELOG_MARKER}"')
    return violations


def issue_is_open(n):
    try:
        result = subprocess.run(
            [GH_INTERACTIVE, "issue", "view", n, "--json", "state", "--jq", ".state"],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            return None
        return result.stdout.strip() == "OPEN"
    except Exception:
        return None


COMMENT_SCOPE_PREFIXES = ["src/", "test/", "scripts/"]


def comment_marker_for(path):
    if re.search(r"\.(mjs|cpp|cc|cxx|hpp|hh|h|c)$", path):
        return "//"
    if re.search(r"\.(test|sql|yml|yaml)$", path):
        return "#"
    return None


def check_deferral_comments(files, dir_):
    violations = []
    for f in files:
        if not any(f.startswith(p) for p in COMMENT_SCOPE_PREFIXES):
            continue
        try:
            content = read_text(os.path.join(dir_, f))
        except OSError:
            continue
        if content is None:
            continue
        marker = comment_marker_for(f)
        lines = content.split("\n")
        for i, line in enumerate(lines):
            marker_at = line.find(marker) if marker else -1
            if marker_at == -1:
                continue
            after_marker = line[marker_at + len(marker):]
            for tag in DEFERRAL_TAGS:
                if re.search(rf"\b{tag}\b", after_marker):
                    m = re.search(r"#(\d+)", line)
                    if not m:
                        violations.append(f'{f}:{i + 1}: {tag} comment without "#<issue>" on the same line')
                    else:
                        open_ = issue_is_open(m.group(1))
                        if open_ is None:
                            violations.append(f"{f}:{i + 1}: could not verify issue #{m.group(1)} is open (gh unavailable)")
                        elif not open_:
                            violations.append(f"{f}:{i + 1}: {tag} cites issue #{m.group(1)}, which is not open")
    return violations


files = list_files(root)
violations = check_denylist(files) + check_changelog(files, root)
violations += check_deferral_comments(files, root)

if violations:
    print("forbid-ledger: FAIL", file=sys.stderr)
    for v in violations:
        print(f"  {v}", file=sys.stderr)
    sys.exit(1)
print("forbid-ledger: PASS")
