#!/usr/bin/env bun
import { $ } from "bun";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const args = process.argv.slice(2);
const rootIdx = args.indexOf("--root");
const root = rootIdx === -1 ? process.cwd() : args[rootIdx + 1];
const usingRealTree = rootIdx === -1;

const DENYLIST = ["PLAN", "STATUS", "PROGRESS", "ROADMAP", "NOTES", "JOURNAL", "TODO"];
const DENY_PATH_PREFIXES = ["docs/plan"];
const CHANGELOG_MARKER = "<!-- generated by just changelog -->";
const DEFERRAL_TAGS = ["TODO", "FIXME", "HACK", "XXX", "WIP"];

async function listFiles(dir) {
  if (usingRealTree) {
    const out = await $`git -C ${dir} ls-files`.text();
    // The hygiene-selftest fixtures are deliberately invalid and scanned only
    // via explicit --root; they are never part of the real-tree sweep.
    return out.split("\n").filter(Boolean).filter((f) => !f.startsWith("test/hygiene-fixtures/"));
  }
  const files = [];
  const walk = (d, prefix) => {
    for (const entry of readdirSync(d)) {
      const full = join(d, entry);
      const rel = prefix ? `${prefix}/${entry}` : entry;
      const st = statSync(full);
      if (st.isDirectory()) walk(full, rel);
      else files.push(rel);
    }
  };
  walk(dir, "");
  return files;
}

function checkDenylist(files) {
  const violations = [];
  for (const f of files) {
    const base = f.split("/").pop();
    for (const pat of DENYLIST) {
      if (base.startsWith(pat)) {
        if (base === "CHANGELOG.md") continue; // not in denylist, but guard just in case
        violations.push(`${f}: filename matches ledger denylist pattern "${pat}*"`);
      }
    }
    for (const prefix of DENY_PATH_PREFIXES) {
      if (f.startsWith(prefix)) {
        violations.push(`${f}: path matches ledger denylist pattern "${prefix}*"`);
      }
    }
  }
  return violations;
}

function checkChangelog(files, dir) {
  const violations = [];
  if (files.includes("CHANGELOG.md")) {
    const content = readFileSync(join(dir, "CHANGELOG.md"), "utf8");
    if (!content.startsWith(CHANGELOG_MARKER)) {
      violations.push(`CHANGELOG.md: must begin with "${CHANGELOG_MARKER}"`);
    }
  }
  return violations;
}

async function issueIsOpen(n) {
  try {
    const out = await $`gh-tsouza issue view ${n} --json state --jq .state`.text();
    return out.trim() === "OPEN";
  } catch {
    return null; // gh unavailable or issue not found
  }
}

const COMMENT_SCOPE_PREFIXES = ["src/", "test/", "scripts/"];

function commentMarkerFor(path) {
  if (/\.(mjs|cpp|cc|cxx|hpp|hh|h|c)$/.test(path)) return "//";
  if (/\.(test|sql|yml|yaml)$/.test(path)) return "#";
  return null; // unknown extension: not scanned for comment-only tags
}

async function checkDeferralComments(files, dir) {
  const violations = [];
  let ghAvailable = true;
  for (const f of files) {
    if (!COMMENT_SCOPE_PREFIXES.some((p) => f.startsWith(p))) continue;
    let content;
    try {
      content = readFileSync(join(dir, f), "utf8");
    } catch {
      continue; // binary or unreadable, skip
    }
    if (content.includes("\0")) continue; // binary
    const marker = commentMarkerFor(f);
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const markerAt = marker ? line.indexOf(marker) : -1;
      if (markerAt === -1) continue; // not a comment line for this file type
      const afterMarker = line.slice(markerAt + marker.length);
      for (const tag of DEFERRAL_TAGS) {
        const re = new RegExp(`\\b${tag}\\b`);
        if (re.test(afterMarker)) {
          const m = line.match(/#(\d+)/);
          if (!m) {
            violations.push(`${f}:${i + 1}: ${tag} comment without "#<issue>" on the same line`);
          } else {
            const open = await issueIsOpen(m[1]);
            if (open === null) {
              ghAvailable = false;
              violations.push(`${f}:${i + 1}: could not verify issue #${m[1]} is open (gh unavailable)`);
            } else if (!open) {
              violations.push(`${f}:${i + 1}: ${tag} cites issue #${m[1]}, which is not open`);
            }
          }
        }
      }
    }
  }
  return { violations, ghAvailable };
}

const files = await listFiles(root);
let violations = [...checkDenylist(files), ...checkChangelog(files, root)];
const deferral = await checkDeferralComments(files, root);
violations = violations.concat(deferral.violations);

if (violations.length > 0) {
  console.error("forbid-ledger: FAIL");
  for (const v of violations) console.error(`  ${v}`);
  process.exit(1);
}
console.log("forbid-ledger: PASS");
