#!/usr/bin/env bun
// make changelog / make changelog-check
// Writes CHANGELOG.md from every Conventional-Commit-titled commit on main
// since the last tag — or since the first commit when no tag exists yet —
// squash-merge titles being the PR titles themselves (Article III.5: squash
// merges only). --check exits non-zero when the file on disk differs from
// what this would write, without touching it (forbid-ledger separately
// enforces the leading marker on any CHANGELOG.md that exists at all).
import { $ } from "bun";
import { readFileSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CONVENTIONAL_COMMITS_RE } from "./lib/conventional-commits.mjs";

const args = process.argv.slice(2);
const check = args.includes("--check");
const rootIdx = args.indexOf("--root");
const root = rootIdx === -1 ? process.cwd() : args[rootIdx + 1];

const MARKER = "<!-- generated by make changelog -->";

async function latestTag() {
  try {
    const out = await $`git -C ${root} describe --tags --abbrev=0`.quiet().text();
    return out.trim() || null;
  } catch {
    return null; // no tag reachable from HEAD
  }
}

async function subjectsSince(tag) {
  const range = tag ? `${tag}..HEAD` : "HEAD";
  const out = await $`git -C ${root} log ${range} --first-parent --pretty=format:%s`.text();
  return out
    .split("\n")
    .filter(Boolean)
    .filter((s) => CONVENTIONAL_COMMITS_RE.test(s));
}

function render(subjects) {
  const lines = [MARKER, "", "# Changelog", "", "## Unreleased"];
  if (subjects.length === 0) {
    lines.push("", "No changes yet.");
  } else {
    lines.push("", ...subjects.map((s) => `- ${s}`));
  }
  lines.push("");
  return lines.join("\n");
}

const tag = await latestTag();
const subjects = await subjectsSince(tag);
const generated = render(subjects);
const path = join(root, "CHANGELOG.md");

if (check) {
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current !== generated) {
    console.error("changelog-check: FAIL");
    console.error(`  ${path} does not match what "make changelog" would write`);
    process.exit(1);
  }
  console.log("changelog-check: PASS");
} else {
  writeFileSync(path, generated);
  console.log(`changelog: wrote ${path} (${subjects.length} entr${subjects.length === 1 ? "y" : "ies"})`);
}
