#!/usr/bin/env python3
"""make changelog / make changelog-check

Writes CHANGELOG.md from every Conventional-Commit-titled commit on main since the last tag -- or since
the first commit when no tag exists yet -- squash-merge titles being the
PR titles themselves (Article III.5: squash merges only). --check exits
non-zero when the file on disk differs from what this would write, without
touching it (forbid-ledger separately enforces the leading marker on any
CHANGELOG.md that exists at all).
"""

import subprocess
import sys
from pathlib import Path

from lib.conventional_commits import CONVENTIONAL_COMMITS_RE

MARKER = "<!-- generated by make changelog -->"


def _root_from_args(args):
    if "--root" in args:
        return Path(args[args.index("--root") + 1])
    return Path.cwd()


def _git(root, args):
    return subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True)


def latestTag(root):
    result = _git(root, ["describe", "--tags", "--abbrev=0"])
    if result.returncode != 0:
        return None  # no tag reachable from HEAD
    out = result.stdout.strip()
    return out or None


def subjectsSince(root, tag):
    rng = f"{tag}..HEAD" if tag else "HEAD"
    result = _git(root, ["log", rng, "--first-parent", "--pretty=format:%s"])
    if result.returncode != 0:
        raise RuntimeError(
            f"git -C {root} log {rng} --first-parent --pretty=format:%s failed "
            f"(exit {result.returncode}): {result.stderr.strip()}"
        )
    return [s for s in result.stdout.split("\n") if s and CONVENTIONAL_COMMITS_RE.match(s)]


def render(subjects):
    lines = [MARKER, "", "# Changelog", "", "## Unreleased"]
    if not subjects:
        lines.append("")
        lines.append("No changes yet.")
    else:
        lines.append("")
        lines.extend(f"- {s}" for s in subjects)
    lines.append("")
    return "\n".join(lines)


def main():
    args = sys.argv[1:]
    check = "--check" in args
    root = _root_from_args(args)

    tag = latestTag(root)
    subjects = subjectsSince(root, tag)
    generated = render(subjects)
    path = root / "CHANGELOG.md"

    if check:
        current = path.read_text(encoding="utf8") if path.exists() else None
        if current != generated:
            print("changelog-check: FAIL", file=sys.stderr)
            print(f"  {path} does not match what \"make changelog\" would write", file=sys.stderr)
            sys.exit(1)
        print("changelog-check: PASS")
    else:
        path.write_text(generated, encoding="utf8")
        entry_word = "entry" if len(subjects) == 1 else "entries"
        print(f"changelog: wrote {path} ({len(subjects)} {entry_word})")


if __name__ == "__main__":
    main()
